### ISSUE TITLE
Feature: add a LocalStorage personal preferences

### ISSUE THREAD

**Issue by tomsihap** [matthieurobin/open-fuji-recipes#4]
When I connect to the website, User can be able to save preferences (filters among other future things). To keep the app being a front-end webapp only and then to avoid managing user accounts, there could be a LocalStorage/cookies system to manage preferences as they are not critical data to keep.

**Comment by matthieurobin** [comment]
Thank you for your feature request.

I'm glad to say that a user is already able to save preferences:
  - config settings (only language for now)
  - filters
  - stars
  
Feel free to reopen the issue if needed
